import { LayoutDocument } from '../types';

/**
 * Generates an Adobe InDesign CS5.5 ExtendScript (.jsx) file that recreates
 * the exact document geometry, text frame, columns, and styles in desktop InDesign.
 */
export const generateInDesignScript = (doc: LayoutDocument): string => {
  const cleanTitle = (doc.title || 'Studio8_Notice').replace(/[^a-zA-Z0-9]/g, '_');
  const safeBody = (doc.bodyText || '').replace(/"/g, '\\"').replace(/\n/g, '\\r');
  const safeKicker = (doc.kicker || '').replace(/"/g, '\\"').replace(/\n/g, '\\r');
  const safeSubHeader = (doc.subHeader || '').replace(/"/g, '\\"');

  const scriptContent = `// Adobe InDesign CS5.5 / CC ExtendScript Automation
// Generated by Studio8 Production Engine v5.5
#target "indesign"

(function() {
    var myDoc = app.documents.add();
    myDoc.viewPreferences.horizontalMeasurementUnits = MeasurementUnits.MILLIMETERS;
    myDoc.viewPreferences.verticalMeasurementUnits = MeasurementUnits.MILLIMETERS;
    myDoc.documentPreferences.pageWidth = 210;
    myDoc.documentPreferences.pageHeight = 297;
    myDoc.documentPreferences.facingPages = false;

    var myPage = myDoc.pages.item(0);

    // Bounding Box Coordinates [Y1, X1, Y2, X2] in mm
    var y1 = ${doc.posY};
    var x1 = ${doc.posX};
    var y2 = ${doc.posY + doc.frameHeight};
    var x2 = ${doc.posX + doc.frameWidth};

    var myFrame = myPage.textFrames.add({
        geometricBounds: [y1, x1, y2, x2],
        textFramePreferences: {
            textColumnCount: ${doc.columns},
            textColumnGutter: ${doc.gutter}
        }
    });

    // Stroke weight
    myFrame.strokeWeight = ${doc.borderWidth || 0.5};
    myFrame.strokeColor = myDoc.colors.item("Black");

    // Populate Copy
    var fullContent = "${safeKicker}\\r\\r" + "${doc.title}\\r" + "${safeSubHeader}\\r\\r" + "${safeBody}";
    myFrame.contents = fullContent;

    // Format Typography
    try {
        myFrame.paragraphs.item(0).appliedFont = app.fonts.item("${doc.fontFamily || 'Helvetica'}");
        myFrame.paragraphs.item(0).pointSize = ${doc.fontSize || 8.5};
        myFrame.paragraphs.item(0).leading = ${doc.lineHeight || 11.2};
        myFrame.paragraphs.item(0).justification = Justification.JUSTIFY_FULL;
    } catch(e) {}

    alert("Studio8 CS5.5 Layout [${cleanTitle}] generated successfully!");
})();
`;

  const blob = new Blob([scriptContent], { type: 'text/javascript;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${cleanTitle}_CS55_Automation.jsx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  return `${cleanTitle}_CS55_Automation.jsx`;
};

/**
 * Export raw standalone vector SVG of the ad layout for vector workflows.
 */
export const exportLayoutToSvg = (doc: LayoutDocument): string => {
  const cleanTitle = (doc.title || 'Studio8_Artwork').replace(/[^a-zA-Z0-9]/g, '_');
  const w = doc.frameWidth * 3.7795; // mm to px (96 dpi)
  const h = doc.frameHeight * 3.7795;

  const svgContent = `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <style>
    .kicker { font-family: 'Helvetica', Arial, sans-serif; font-size: 11px; font-weight: bold; text-anchor: middle; }
    .title { font-family: 'Helvetica', Arial, sans-serif; font-size: 14px; font-weight: bold; text-decoration: underline; text-anchor: middle; }
    .sub { font-family: 'Helvetica', Arial, sans-serif; font-size: 10px; font-weight: bold; text-anchor: middle; }
    .body { font-family: 'Helvetica', Arial, sans-serif; font-size: 9px; line-height: 12px; }
  </style>
  <rect x="1" y="1" width="${w - 2}" height="${h - 2}" fill="#ffffff" stroke="#000000" stroke-width="${doc.borderWidth || 0.5}" />
  <text x="${w / 2}" y="24" class="kicker">${doc.kicker.split('\n')[0] || ''}</text>
  <text x="${w / 2}" y="42" class="title">${doc.title || 'NOTIS IKLAN'}</text>
  <text x="${w / 2}" y="58" class="sub">${doc.subHeader || ''}</text>
</svg>`;

  const blob = new Blob([svgContent], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${cleanTitle}_Vector.svg`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);

  return `${cleanTitle}_Vector.svg`;
};
